feat: fix casing in policies
Azure/azure-monitor-baseline-alerts pull request #238
Opened 2024-06-10 14:59 UTC by steph409

# Overview/Summary
I started to implement the terraform code for the deployment of the baseline policies here: https://github.com/steph409/tf-azure-monitor-baseline-alerts

Terraform is case sensitive, so wants to change the parameter e.g. from "defaultvalue" to "defaultValue". I already made one PR for it, but did not change it everywhere apparently.

## This PR fixes/adds/changes/removes

1. change frontdoor to frontDoor consistently
2. change allowedvalue to allowedValue consistently
3. change defaultvalue to defaultValue consistently

### Breaking Changes
None

## As part of this Pull Request I have

- [X] Read the Contribution Guide and ensured this PR is compliant with the guide
- [X] Checked for duplicate [Pull Requests](https://github.com/Azure/azure-monitor-baseline-alerts/pulls)
- [ ] Associated it with relevant [GitHub Issues](https://github.com/Azure/azure-monitor-baseline-alerts/issues) or ADO Work Items (Internal Only)
- [X] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/azure-monitor-baseline-alerts/)
- [ ] Ensured PR tests are passing
- [ ] Updated relevant and associated documentation (e.g. Contribution Guide, Docs etc.)

2024-06-11 21:46 UTC, arjenhuitema requested changes
Hi @steph409, thanks for submitting these changes. Please also update the version of the policy. String/Metadata changes are patch version updates.

Patch Version
1.0.0 --> 1.0.1

2024-06-12 07:28 UTC, steph409 commented
@arjenhuitema done :)

2024-06-12 21:19 UTC, arjenhuitema approved these changes
LGTM. Thanks @steph409.

2024-06-12 21:29 UTC, arjenhuitema approved these changes

2024-06-12 21:30 UTC, merged